Frontend:
  impl: SimpleO3
  clock_ratio: 8
  num_expected_insts: 500000
  traces:
    - traces/layer0_ramulator_trace.trace

  Translation:
    impl: NoTranslation
    max_addr: 2147483648
              

MemorySystem:
  impl: PathORAM
  clock_ratio: 3
  max_addr: 2147483648
  block_size: 256
  z_blocks: 4
  arity: 2
  stash_size: 8192
  crypt_decrypt_delay: 1
  hash_delay: 10

  DRAM:
    impl: HBM2
    org:
      preset: HBM2_2Gb
      channel: 1
    timing:
      preset: HBM2_2Gbps 

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy
      cap: 4
    plugins:

  AddrMapper:
    impl: RoBaRaCoCh
